spring.datasource.url=jdbc:postgresql://localhost:5432/smartgrid
spring.datasource.username=ashish
spring.datasource.password=202403002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true